microservice1:
  image: 'jlr2/micro-service-spring-boot'
  expose:
    - "8080"
microservice2:
  image: 'jlr2/micro-service-spring-boot'
  expose:
    - "8080"
loadbalancer:
  image: 'dockercloud/haproxy:latest'
  links:
    - microservice1
    - microservice2
  ports:
    - '80:80'
