version: '2'
services:
  microservicio:
    image: 'jlr2/micro-service-spring-boot'
    expose:
      - "8080"
    ports:
      - 8282:8080
    tty: true
    container_name: microserviciolocal_pruebas

