version: '2'
services:
  microservicio-app:
    image: 'jlr2/microservicio-app:1.0'
    expose:
      - "8081"
    ports:
      - 8081:8081
    tty: true
    container_name: microservicio-app 
    depends_on: 
      - microservicio-sccs
  microservicio-sccs:
    image: 'jlr2/microservicio-sccs:1.0'
    expose:
      - "8083"
    ports:
      - 8083:8083
    tty: true
    container_name: microservicio-sccs

